/*
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.ui.tests;

import com.google.inject.Injector;
import eu.stamp.mfts.ui.internal.MftsActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MFTSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MftsActivator.getInstance().getInjector("eu.stamp.mfts.MFTS");
	}

}
