/*
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMFTSScopeProvider extends DelegatingScopeProvider {
}
