/*
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MFTSRuntimeModule extends AbstractMFTSRuntimeModule {
}
