/*
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MFTSStandaloneSetup extends MFTSStandaloneSetupGenerated {

	def static void doSetup() {
		new MFTSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
