/*
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.ide

import com.google.inject.Guice
import eu.stamp.mfts.MFTSRuntimeModule
import eu.stamp.mfts.MFTSStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MFTSIdeSetup extends MFTSStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MFTSRuntimeModule, new MFTSIdeModule))
	}
	
}
