/**
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.ide;

import eu.stamp.mfts.ide.AbstractMFTSIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MFTSIdeModule extends AbstractMFTSIdeModule {
}
