/**
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.stamp.mfts.MFTSRuntimeModule;
import eu.stamp.mfts.MFTSStandaloneSetup;
import eu.stamp.mfts.ide.MFTSIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MFTSIdeSetup extends MFTSStandaloneSetup {
  @Override
  public Injector createInjector() {
    MFTSRuntimeModule _mFTSRuntimeModule = new MFTSRuntimeModule();
    MFTSIdeModule _mFTSIdeModule = new MFTSIdeModule();
    return Guice.createInjector(Modules2.mixin(_mFTSRuntimeModule, _mFTSIdeModule));
  }
}
