/*
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MFTSAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/stamp/mfts/parser/antlr/internal/InternalMFTS.tokens");
	}
}
