/**
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.validation;

import eu.stamp.mfts.validation.AbstractMFTSValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MFTSValidator extends AbstractMFTSValidator {
}
