/**
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.mFTS;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extern Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.stamp.mfts.mFTS.ExternExpression#getExpression <em>Expression</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.ExternExpression#getSegments <em>Segments</em>}</li>
 * </ul>
 *
 * @see eu.stamp.mfts.mFTS.MFTSPackage#getExternExpression()
 * @model
 * @generated
 */
public interface ExternExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' attribute.
   * @see #setExpression(String)
   * @see eu.stamp.mfts.mFTS.MFTSPackage#getExternExpression_Expression()
   * @model
   * @generated
   */
  String getExpression();

  /**
   * Sets the value of the '{@link eu.stamp.mfts.mFTS.ExternExpression#getExpression <em>Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' attribute.
   * @see #getExpression()
   * @generated
   */
  void setExpression(String value);

  /**
   * Returns the value of the '<em><b>Segments</b></em>' containment reference list.
   * The list contents are of type {@link eu.stamp.mfts.mFTS.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Segments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segments</em>' containment reference list.
   * @see eu.stamp.mfts.mFTS.MFTSPackage#getExternExpression_Segments()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getSegments();

} // ExternExpression
