/**
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.mFTS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service Interface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.stamp.mfts.mFTS.ServiceInterface#getName <em>Name</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.ServiceInterface#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.ServiceInterface#getSends <em>Sends</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.ServiceInterface#getReceives <em>Receives</em>}</li>
 * </ul>
 *
 * @see eu.stamp.mfts.mFTS.MFTSPackage#getServiceInterface()
 * @model
 * @generated
 */
public interface ServiceInterface extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see eu.stamp.mfts.mFTS.MFTSPackage#getServiceInterface_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link eu.stamp.mfts.mFTS.ServiceInterface#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link eu.stamp.mfts.mFTS.PlatformAnnotation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see eu.stamp.mfts.mFTS.MFTSPackage#getServiceInterface_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<PlatformAnnotation> getAnnotations();

  /**
   * Returns the value of the '<em><b>Sends</b></em>' reference list.
   * The list contents are of type {@link eu.stamp.mfts.mFTS.Message}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sends</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sends</em>' reference list.
   * @see eu.stamp.mfts.mFTS.MFTSPackage#getServiceInterface_Sends()
   * @model
   * @generated
   */
  EList<Message> getSends();

  /**
   * Returns the value of the '<em><b>Receives</b></em>' reference list.
   * The list contents are of type {@link eu.stamp.mfts.mFTS.Message}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Receives</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receives</em>' reference list.
   * @see eu.stamp.mfts.mFTS.MFTSPackage#getServiceInterface_Receives()
   * @model
   * @generated
   */
  EList<Message> getReceives();

} // ServiceInterface
