/**
 * generated by Xtext 2.12.0
 */
package eu.stamp.mfts.mFTS.impl;

import eu.stamp.mfts.mFTS.MFTSPackage;
import eu.stamp.mfts.mFTS.Message;
import eu.stamp.mfts.mFTS.PlatformAnnotation;
import eu.stamp.mfts.mFTS.ServiceInterface;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Service Interface</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eu.stamp.mfts.mFTS.impl.ServiceInterfaceImpl#getName <em>Name</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.impl.ServiceInterfaceImpl#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.impl.ServiceInterfaceImpl#getSends <em>Sends</em>}</li>
 *   <li>{@link eu.stamp.mfts.mFTS.impl.ServiceInterfaceImpl#getReceives <em>Receives</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ServiceInterfaceImpl extends MinimalEObjectImpl.Container implements ServiceInterface
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAnnotations() <em>Annotations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotations()
   * @generated
   * @ordered
   */
  protected EList<PlatformAnnotation> annotations;

  /**
   * The cached value of the '{@link #getSends() <em>Sends</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSends()
   * @generated
   * @ordered
   */
  protected EList<Message> sends;

  /**
   * The cached value of the '{@link #getReceives() <em>Receives</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReceives()
   * @generated
   * @ordered
   */
  protected EList<Message> receives;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ServiceInterfaceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MFTSPackage.Literals.SERVICE_INTERFACE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MFTSPackage.SERVICE_INTERFACE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<PlatformAnnotation> getAnnotations()
  {
    if (annotations == null)
    {
      annotations = new EObjectContainmentEList<PlatformAnnotation>(PlatformAnnotation.class, this, MFTSPackage.SERVICE_INTERFACE__ANNOTATIONS);
    }
    return annotations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Message> getSends()
  {
    if (sends == null)
    {
      sends = new EObjectResolvingEList<Message>(Message.class, this, MFTSPackage.SERVICE_INTERFACE__SENDS);
    }
    return sends;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Message> getReceives()
  {
    if (receives == null)
    {
      receives = new EObjectResolvingEList<Message>(Message.class, this, MFTSPackage.SERVICE_INTERFACE__RECEIVES);
    }
    return receives;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MFTSPackage.SERVICE_INTERFACE__ANNOTATIONS:
        return ((InternalEList<?>)getAnnotations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MFTSPackage.SERVICE_INTERFACE__NAME:
        return getName();
      case MFTSPackage.SERVICE_INTERFACE__ANNOTATIONS:
        return getAnnotations();
      case MFTSPackage.SERVICE_INTERFACE__SENDS:
        return getSends();
      case MFTSPackage.SERVICE_INTERFACE__RECEIVES:
        return getReceives();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MFTSPackage.SERVICE_INTERFACE__NAME:
        setName((String)newValue);
        return;
      case MFTSPackage.SERVICE_INTERFACE__ANNOTATIONS:
        getAnnotations().clear();
        getAnnotations().addAll((Collection<? extends PlatformAnnotation>)newValue);
        return;
      case MFTSPackage.SERVICE_INTERFACE__SENDS:
        getSends().clear();
        getSends().addAll((Collection<? extends Message>)newValue);
        return;
      case MFTSPackage.SERVICE_INTERFACE__RECEIVES:
        getReceives().clear();
        getReceives().addAll((Collection<? extends Message>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MFTSPackage.SERVICE_INTERFACE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MFTSPackage.SERVICE_INTERFACE__ANNOTATIONS:
        getAnnotations().clear();
        return;
      case MFTSPackage.SERVICE_INTERFACE__SENDS:
        getSends().clear();
        return;
      case MFTSPackage.SERVICE_INTERFACE__RECEIVES:
        getReceives().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MFTSPackage.SERVICE_INTERFACE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MFTSPackage.SERVICE_INTERFACE__ANNOTATIONS:
        return annotations != null && !annotations.isEmpty();
      case MFTSPackage.SERVICE_INTERFACE__SENDS:
        return sends != null && !sends.isEmpty();
      case MFTSPackage.SERVICE_INTERFACE__RECEIVES:
        return receives != null && !receives.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ServiceInterfaceImpl
